FROM --platform=$BUILDPLATFORM golang:1.21@sha256:19600fdcae402165dcdab18cb9649540bde6be7274dedb5d205b2f84029fe909 as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM alpine:3.18@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-github-comment"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-github-comment"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-github-comment"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-github-comment"

COPY --from=build /src/dist/wp-github-comment /bin/wp-github-comment
ENTRYPOINT ["/bin/wp-github-comment"]
