FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.22@sha256:a1dc4081faf597ac3401677edc31d9fcf1eada1884791033b93d35fa7351791d as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.20@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-github-comment"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-github-comment"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-github-comment"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-github-comment"

COPY --from=build /src/dist/wp-github-comment /bin/wp-github-comment
ENTRYPOINT ["/bin/wp-github-comment"]
