FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.23.3@sha256:3694e364a0357a6e885569d3bdd097f7b36839bc4fb0df2af33d411b37e27e59 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.20@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-github-comment"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-github-comment"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-github-comment"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-github-comment"

COPY --from=build /src/dist/wp-github-comment /bin/wp-github-comment
ENTRYPOINT ["/bin/wp-github-comment"]
